"""Add title and description to Recipe

Revision ID: dd3e1e72cb44
Revises: e1f4e531f348
Create Date: 2025-05-22 17:34:18.179226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3e1e72cb44'
down_revision = 'e1f4e531f348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
